version: '3'

services:

  nats-server:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222 # puerto para ver clientes conectados

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3002
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
 
  # products-ms:
  #   build: ./products-ms
  #   volumes:
  #     - ./products-ms/src:/usr/src/app/src
  #   command: pnpm run start:dev
  #   environment:
  #     - PORT=3002
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=file:./dev.db
 
  # orders-db:
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ordersdb
 
  # order-ms:
  #   depends_on:
  #     - orders-db
  #   build: ./orders-ms
  #   volumes:
  #     - ./orders-ms/src:/usr/src/app/src
  #   command: pnpm run start:dev
  #   environment:
  #     - PORT=3003
  #     - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
  #     - NATS_SERVERS=nats://nats-server:4222 
